terafoundation:
    environment: 'development'
    connectors:
        elasticsearch:
            default:
                host:
                    - "<ELASTICSEARCH_HOST>:<ELASTICSEARCH_PORT>"
        elasticsearch-next:
            default:
                node:
                    - "<ELASTICSEARCH_HOST>:<ELASTICSEARCH_PORT>"
teraslice:
    assets_directory: '/app/assets/'
    cluster_manager_type: "kubernetes"
    master: false
    master_hostname: "teraslice-master"
    name: "teracluster"
