terafoundation:
    connectors:
        elasticsearch-next:
            default:
                node:
                    - "<<OPENSEARCH_HOST>:<OPENSEARCH_PORT>"
teraslice:
    assets_directory: '/app/assets/'
    cluster_manager_type: "kubernetesV2"
    master: false
    master_hostname: "teraslice-master"
    name: "teracluster"
