terafoundation:
    connectors:
        elasticsearch-next:
            default:
                node:
                    - "<OPENSEARCH_HOST>:<OPENSEARCH_PORT>"
teraslice:
    assets_directory: "/app/assets/"
    cluster_manager_type: "kubernetesV2"
    master: true
    master_hostname: "127.0.0.1"
    name: "teracluster"
