terafoundation:
    environment: 'development'
    workers: 8

    connectors:
        # ***********************
        # Elastic Search Configuration
        # ***********************
        elasticsearch:
            default:
                host:
                    - "elasticsearch:9200"

teraslice:
    ops_directory: '/app/source/examples/ops/'

    cluster:
        master: true
        master_hostname: "127.0.0.1"
        name: "teracluster"
