terafoundation:

    connectors:
        # ***********************
        # Elastic Search Configuration
        # ***********************
        elasticsearch-next:
            default:
                node:
                    - "http://localhost:9200"

teraslice:
    master: false
    master_hostname: "teraslice-master"
    name: "teracluster"
