terafoundation:
    environment: 'development'

    connectors:
        # ***********************
        # Elastic Search Configuration
        # ***********************
        elasticsearch:
            default:
                host:
                    - "127.0.0.1:9200"
        elasticsearch-next:
            default:
                node:
                    - "http://localhost:9200"

teraslice:
    master: false
    master_hostname: "teraslice-master"
    name: "teracluster"
