apiVersion: v2
name: teraslice-chart
description: Teraslice -  Distributed computing platform for processing JSON data
home: https://github.com/terascope/teraslice
icon: https://terascope.github.io/teraslice/img/logo.png
type: application
version: 3.4.0
appVersion: v3.2.0
sources:
  - https://github.com/terascope/teraslice
keywords:
  - teraslice
  - elasticsearch
