apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  private.key: {{ .Values.privateKey | replace "\\n" "\n" | quote }}
  public.crt: {{ .Values.publicCert | replace "\\n" "\n" | quote }}
  rootCA.pem: {{ .Values.rootCA | replace "\\n" "\n" | quote }}

